name: gemeinde_app
description: Gemeinde App MVP
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

  http: ^1.2.2
  flutter_secure_storage: ^9.0.0
  file_picker: ^10.3.8
  path_provider: ^2.1.4


flutter:
  uses-material-design: true
