name: gemeinde_app
description: Gemeinde App MVP
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies: http: ^1.2.2

  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
